/* eslint-disable */

// PRODUCTS LIST
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_ERROR = 'PRODUCT_LIST_ERROR'

// PRODUCT DETAILS
export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_ERROR = 'PRODUCT_DETAILS_ERROR'

// CART ACTIONS
export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'

// USER ACTIONS
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_ERROR = 'USER_UPDATE_ERROR'

// ORDER ACTIONS 
export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_ERROR = 'ORDER_CREATE_ERROR'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_ERROR = 'ORDER_DETAILS_ERROR'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_ERROR = 'ORDER_PAY_ERROR'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const ORDERS_USER_REQUEST = 'ORDER_USER_REQUEST'
export const ORDERS_USER_SUCCESS = 'ORDER_USER_SUCCESS'
export const ORDERS_USER_ERROR = 'ORDER_USER_ERROR'

export const ORDERS_ADMIN_REQUEST = 'ORDER_ADMIN_REQUEST'
export const ORDERS_ADMIN_SUCCESS = 'ORDER_ADMIN_SUCCESS'
export const ORDERS_ADMIN_ERROR = 'ORDER_ADMIN_ERROR'